name: Build and Push Frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/visitor-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/visitor-frontend:latest
