name: Build and Push Backend

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/visitor-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/visitor-backend:latest
